import Bluesky from '~/components/bluesky.vue'

export const projects = [
	{
		label: 'Tempest',
		site: 'https://tempestphp.com',
		repository: 'https://github.com/tempestphp/tempest-framework',
		description:
			'Innovative, modern and elegant PHP framework. With zero configuration and zero boilerplate, it provides the architectural freedom to focus entirely on business logic.',
		icon: 'brand:tempest',
		iconUrl: 'https://raw.githubusercontent.com/tempestphp/.github/refs/heads/main/logo_2024/tempest-logo.svg',
		role: 'core-maintainer' as const,
		featured: true,
	},
	{
		label: 'Hybridly',
		site: 'https://hybridly.dev',
		repository: 'https://github.com/hybridly/hybridly',
		description:
			'Solution to develop server-driven, client-rendered applications on top of Laravel and Vue. An alternative to Inertia, written with TypeScript and developer experience in mind.',
		icon: 'brand:hybridly',
		iconUrl: 'https://raw.githubusercontent.com/hybridly/hybridly/0.x/.github/assets/logo.svg',
		featured: true,
	},
	{
		label: 'Preset',
		site: 'https://preset.dev',
		repository: 'https://github.com/preset/preset',
		description: 'Elegant, ecosystem-agnostic preset mechanism. Define changes and apply them in your new projects in just one command.',
		iconUrl: 'https://raw.githubusercontent.com/preset/preset/main/.github/assets/logo-no-bg.svg',
		featured: true,
	},
	{
		label: 'Vite for Laravel',
		site: 'https://laravel-vite.innocenzi.dev/',
		repository: 'https://github.com/innocenzi/laravel-vite',
		description: 'Vite integration for Laravel. It was the de-facto solution before Laravel released their official integration.',
		icon: 'brand:vite-for-laravel',
		deprecated: true,
		createdAt: '2021-02-09',
	},
	{
		label: 'Awesome Tailwind CSS',
		description: 'A curated list of awesome Tailwind CSS resources.',
		repository: 'https://github.com/aniftyco/awesome-tailwindcss',
		created_at: '2020-08-31',
		role: 'co-maintainer' as const,
	},
	{
		label: 'Encore for Laravel',
		repository: 'https://github.com/innocenzi/laravel-encore',
		description: 'Webpack Encore integration for Laravel.',
		deprecated: true,
		created_at: '2020-06-12',
	},
	{
		label: 'Rename',
		description: 'Command-line interface to batch-rename files from your preferred editor.',
		repository: 'https://github.com/innocenzi/rename',
		created_at: '2021-09-06',
	},
	{
		label: 'vite-plugin-run',
		description: 'Run commands when Vite starts, builds, or when a file changes.',
		repository: 'https://github.com/innocenzi/vite-plugin-run',
		created_at: '2022-07-08',
	},
	{
		label: 'vite-plugin-mjml',
		description: 'Compiles MJML templates during development and when Vite builds.',
		repository: 'https://github.com/innocenzi/vite-plugin-mjml',
		created_at: '2022-04-13',
	},
	{
		label: 'Forge recipe for Deployer',
		description: 'Recipe that helps implementing zero-downtime deployments on Laravel Forge.',
		repository: 'https://github.com/innocenzi/deployer-recipe-forge',
		created_at: '2023-09-09',
		deprecated: true,
	},
	{
		label: 'Tailwind CSS theming',
		description: 'CSS-variables-based swappable themes for Tailwind CSS.',
		repository: 'https://github.com/innocenzi/tailwindcss-theming',
		created_at: '2019-10-04',
		deprecated: true,
	},
	{
		label: 'Awesome Inertia',
		description: 'A curated list of awesome Inertia.js resources.',
		repository: 'https://github.com/innocenzi/awesome-inertiajs',
		created_at: '2020-08-31',
	},
	{
		repository: 'https://github.com/innocenzi/avatar',
		site: 'https://avatar.innocenzi.dev',
		label: 'Avatar',
		description: 'Simple online tool for cropping images from an URL, your clipboard, or your disk.',
		created_at: '2021-03-27',
	},
	{
		label: 'vite-plugin-run',
		description: 'Run commands when Vite starts, builds, or when a file changes.',
		repository: 'https://github.com/innocenzi/vite-plugin-run',
		created_at: '2022-07-08',
	},
	{
		label: 'Tailwind CSS scroll-snap',
		description: "Adds scroll-snap utilities to Tailwind CSS. This plugin has been incorporated in Tailwind's core.",
		repository: 'https://github.com/innocenzi/tailwindcss-scroll-snap',
		created_at: '2020-01-07',
		deprecated: true,
	},
	{
		label: 'Vertical slices preset for Laravel',
		description: 'Preset that configures a vertical slice architecture on a fresh Laravel project.',
		repository: 'https://github.com/laravel-presets/slices',
		created_at: '2023-09-14',
	},
]

export const stack = [
	{ label: 'Tempest', icon: 'brand:tempest', url: 'https://tempestphp.com' },
	{ label: 'Vue', icon: 'tabler:brand-vue', url: 'https://vuejs.org' },
	{ label: 'Inertia', icon: 'tabler:brand-inertia', url: 'https://inertiajs.com' },
	{ label: 'Laravel', icon: 'tabler:brand-laravel', url: 'https://laravel.com' },
	{ label: 'Tailwind CSS', icon: 'tabler:brand-tailwind', url: 'https://tailwindcss.com' },
	{ label: 'TypeScript', icon: 'tabler:brand-typescript', url: 'https://www.typescriptlang.org' },
	{ label: 'PHP', icon: 'tabler:brand-php', url: 'https://www.php.net' },
	{ label: 'Bun', icon: 'brand:bun', url: 'https://bun.sh' },
	{ label: 'Nuxt', icon: 'tabler:brand-nuxt', url: 'https://nuxt.com' },
	{ label: 'Motion', icon: 'brand:motion', url: 'https://motion.dev' },
	{ label: 'Git', icon: 'tabler:brand-git', url: 'https://git-scm.com' },
	{ label: 'Postgres', icon: 'carbon:database-postgresql', url: 'https://postgresql.com' },
	{ label: 'Figma', icon: 'tabler:brand-figma', url: 'https://figma.com' },
	{ label: 'Reka UI', icon: 'brand:reka-ui', url: 'https://reka-ui.com' },
	{ label: 'Redis', icon: 'simple-icons:redis', url: 'https://redis.com' },
]

export const socials = [
	{ label: 'GitHub', url: 'https://github.com/innocenzi', handle: '@innocenzi', icon: 'tabler:brand-github' },
	{ label: 'Bluesky', url: 'https://bsky.app/profile/innocenzi.dev', handle: 'innocenzi.dev', icon: Bluesky },
	{ label: 'Twitter', url: 'https://twitter.com/enzoinnocenzi', handle: '@enzoinnocenzi', icon: 'tabler:brand-twitter' },
	{ label: 'Email', url: 'mailto:hi@innocenzi.dev', handle: 'hi@innocenzi.dev', icon: 'tabler:mail' },
]

export const hardware = [
	{
		label: 'MacBook Pro 14"',
		specifications: 'M1, 16GB RAM, 500GB',
		comment: 'my work machine',
		url: 'https://www.apple.com/macbook-pro/',
		icon: 'tabler:device-laptop',
	},
	{
		label: 'Custom gaming PC',
		specifications: 'Hyte Y60, Ryzen 7 7800X3D, 2x 980 Pro 2TB, RTX 4090 FE, 32GB',
		comment: undefined,
		url: 'https://pcpartpicker.com/',
		icon: 'tabler:device-desktop',
	},
	{
		label: 'NuPhy Gem80',
		specifications: 'Mint switches, QWERTY international layout',
		comment: undefined,
		url: 'https://nuphy.com/products/gem80',
		icon: 'tabler:keyboard',
	},
	{
		label: 'G502X Lightspeed',
		specifications: undefined,
		comment: 'I would choose the MX Master if I did not need the extra buttons for gaming',
		url: 'https://www.logitechg.com/en-us/shop/p/g502-x-plus-wireless-lightforce.910-006160',
		icon: 'tabler:mouse',
	},
	{
		label: 'Arctis Nova Pro',
		specifications: undefined,
		comment: 'I love it because it is wireless and has two batteries',
		url: 'https://steelseries.com/gaming-headsets/arctis-nova-pro-wireless',
		icon: 'tabler:headphones',
	},
	{
		label: 'AV Access 8K KVM Switch',
		specifications: '8KSW21-KVM',
		comment: 'for switching between personal and work computers',
		url: 'https://www.avaccess.com/products/8ksw21-kvm/',
		icon: 'tabler:switch-horizontal',
	},
	{
		label: 'Shure MV7',
		specifications: undefined,
		comment: 'On an Elgato Wave Mic Arm, using the XLR dock',
		url: 'https://www.shure.com/en-US/products/microphones/mv7',
		icon: 'tabler:microphone',
	},
	{
		label: 'Elgato Stream Deck+',
		specifications: undefined,
		comment: 'I use it to control sound and lights using Home Assistant',
		url: 'https://www.elgato.com/us/en/p/stream-deck-plus-black',
		icon: 'tabler:device-gamepad',
	},
	{
		label: 'Elgato Facecam',
		specifications: '1080p60',
		comment: undefined,
		url: 'https://www.elgato.com/us/en/p/facecam',
		icon: 'tabler:video',
	},
	{
		label: 'AirPods Pro',
		specifications: 'Second generation, USB-C',
		comment: 'bought these for the noise cancellation despite being on Android',
		url: 'https://www.apple.com/airpods-pro/',
		icon: 'tabler:headset',
	},
	{
		label: 'Pixel 8 Pro',
		specifications: 'Black, 12GB',
		comment: undefined,
		url: 'https://store.google.com/category/phones?hl=fr',
		icon: 'tabler:device-mobile',
	},
	{
		label: 'Dell G2724D',
		specifications: '2x 27" 2560x1440, 165Hz',
		comment: 'the secondary one is mounted vertically',
		url: 'https://www.dell.com/en-us/shop/dell-27-gaming-monitor-g2724d/apd/210-bhxc/monitors-monitor-accessories',
		icon: 'tabler:device-desktop-analytics',
	},
	{
		label: 'Flexispot E7 Pro',
		specifications: undefined,
		comment: 'I generally work standing, and lower it for gaming',
		url: 'https://www.flexispot.com/flexispot-best-standing-desk-e7pro',
		icon: 'tabler:layout-board',
	},
	{
		label: 'Yeelight Monitor Light Bar Pro',
		specifications: undefined,
		comment: 'Screen light bar for reducing eye strain, set up on Home Assistant',
		url: 'https://store.yeelight.com/collections/monitor-light-bar/products/yeelight-pura-monitor-light-bar-pro',
		icon: 'tabler:bulb',
	},
	{
		label: 'Home Assistant Green',
		specifications: 'With ZBT-1',
		comment: 'my whole house is automated',
		url: 'https://www.home-assistant.io/green',
		icon: 'tabler:smart-home',
	},
]

export const software = [
	{
		label: 'Code',
		description: 'My primary editor, I use it for PHP, TypeScript and everything else',
		url: 'https://code.visualstudio.com',
		icon: 'tabler:brand-vscode',
	},
	{
		label: 'Zed',
		description: 'My secondary editor, I use it sometimes and wait for it to mature',
		url: 'https://zed.dev',
		icon: 'tabler:code',
	},
	{
		label: 'Zen',
		description: 'My main browser, I love the minimalism',
		url: 'https://zen-browser.app/',
		icon: 'tabler:browser',
	},
	{
		label: 'Ghostty',
		description: "It's lightweight and completely customizable",
		url: 'https://ghostty.org/',
		icon: 'tabler:terminal',
	},
	{
		label: 'Raycast',
		description: 'My favorite productivity software, both on macOS and Windows',
		url: 'https://raycast.com',
		icon: 'tabler:command',
	},
	{
		label: 'NearDrop',
		description: 'Installed on macOS to share files from my Android',
		url: 'https://github.com/grishka/NearDrop',
		icon: 'tabler:share',
	},
	{
		label: 'QuickShare',
		description: 'Installed on Windows to share files from my Android',
		url: 'https://www.android.com/better-together/quick-share-app/',
		icon: 'tabler:share',
	},
	{
		label: 'Fastmail',
		description: 'I have multiple email addresses with different domains',
		url: 'https://www.fastmail.com',
		icon: 'tabler:mail',
	},
	{
		label: 'Yaak',
		description: 'Modern API client that I love for its minimalism',
		url: 'https://yaak.app',
		icon: 'tabler:api',
	},
	{
		label: '1Password',
		description: 'Password manager for both work and my family',
		url: 'https://1password.com',
		icon: 'tabler:key',
	},
	{
		label: 'TablePlus',
		description: "Works with Raycast, but I'm waiting for SQL Studio to release",
		url: 'https://tableplus.com',
		icon: 'tabler:database',
	},
	{
		label: 'DBngin',
		description: 'Database engine manager for local development',
		url: 'https://dbngin.com',
		icon: 'tabler:database-cog',
	},
	{
		label: 'Medis',
		description: 'Redis GUI client for managing Redis databases',
		url: 'https://getmedis.com',
		icon: 'tabler:database-search',
	},
	{
		label: 'Herd',
		description: 'Local PHP development environment',
		url: 'https://herd.laravel.com',
		icon: 'tabler:brand-laravel',
	},
	{
		label: 'Ray',
		description: 'Debugging interface for PHP',
		url: 'https://myray.app',
		icon: 'tabler:bug',
	},
	{
		label: 'Affinity',
		description: 'All-in-one design suite',
		url: 'https://www.affinity.studio/',
		icon: 'tabler:palette',
	},
	{
		label: 'Proton VPN',
		description: "I rarely use it but it's one of the few good VPNs",
		url: 'https://protonvpn.com',
		icon: 'tabler:shield-lock',
	},
	{
		label: 'Linear',
		description: 'We use Linear at work for project management',
		url: 'https://linear.app',
		icon: 'tabler:checkup-list',
	},
	{
		label: 'Wave Link',
		description: 'Manages the sound of each application, both on macOS and Windows',
		url: 'https://www.elgato.com/us/en/s/downloads',
		icon: 'tabler:volume',
	},
	{
		label: 'Netlify',
		description: 'All my static websites are hosted here',
		url: 'https://netlify.com',
		icon: 'tabler:world',
	},
	{
		label: 'Cloudflare',
		description: 'All my domains are registered here, and I use R2 a lot',
		url: 'https://cloudflare.com',
		icon: 'tabler:cloud',
	},
	{
		label: 'Hetzner',
		description: 'Server hosting for everything that needs a server',
		url: 'https://www.hetzner.com',
		icon: 'tabler:server',
	},
]
